# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Pallakku-GPU',
                'doc_host': 'https://kurianbenoy.github.io',
                'git_url': 'https://github.com/kurianbenoy/Pallakku-GPU',
                'lib_path': 'Pallakku_GPU'},
  'syms': {'Pallakku_GPU.core': {'Pallakku_GPU.core.foo': ('core.html#foo', 'Pallakku_GPU/core.py')}}}
